### ISSUE TITLE
Conflicting Refs : Update `taxa_obs` and related mecanics to include optional `parent_taxa_name`

### ISSUE THREAD

**Issue by vincent-beauregard-ielab** [ReseauBiodiversiteQuebec/atlas-db#105]

**Comment by vcameron1** [comment]
Les modifications apportées pour inclure parent_scientific_name à taxa_obs et pour utiliser cette information dans la sélection du best_ref sont excellentes.

À la lumière des discussion que nous avons eu hier, la fonction 'fix_taxa_obs_parent_scientific_name' est à modifier. Plusieurs lignes de la table taxa_obs peuvent avoir le même `scientific_name` et représenter des taxons différents. C'est la situation qui nous cause actuellement le plus de problèmes dans la sélection du best_ref. La fonction  'fix_taxa_obs_parent_scientific_name' dans sa forme actuelle ajoute le `parent_scientific_name` à toutes les lignes correspondant au `scientific_name`, c-a-d que les différents organismes répondant au même nom seront tous identifiés comme appartenant au même `parent_scientific_name`, ce qui n'est pas le cas.

Je suggère de modifier la fonction de façon à prendre le taxa_obs.id en argument plutôt que le `scientific_name`.

**Comment by vcameron1** [comment]
- [ ] Add taxa_vernacular update to the process of updating with parent_scientific_name
